//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiAgenda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asignatura()
        {
            this.Notas = new HashSet<Notas>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Semestre { get; set; }
        public string Seccion { get; set; }
        public string Docente { get; set; }
        public int Estado { get; set; }
    
        public virtual Asistencia Asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notas> Notas { get; set; }
        public virtual Examen Examen { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
